### ISSUE TITLE
Is having main collection interfaces always extending IteratorAggregate the best option?

### ISSUE THREAD

**Issue by WesNetmo** [morrisonlevi/Ardent#26]
Couldn't be more convenient, sometimes, to implement Traversable using Iterator?

interface Map extends \ArrayAccess, \Countable, Enumerable { ... }
->
interface Map extends \ArrayAccess, \Countable, Collection { ... }

**Comment by hakre** [comment]
I won't call it an external iterator, it's just like with a factory method that you delegate the iterator creation to the ConcreteMap sublcass(es) which is a working concept to re-use Iterators and put away the duties to have the iterator implemented in each ConcreteMap.

You also do not needlessly copy arrays or reference them. You can create an abstract base-class with a protected property that keeps the array and then have the ConcreteMap as well as the ConcreteIterator extend from it. Then the ConcreteIterator can access the array of the ConcreteMap (something like friend classes).

**Comment by morrisonlevi** [comment]
Closing – I still feel like external iterators should be the default.
