### ISSUE TITLE
Method visibility

### ISSUE THREAD

**Issue by JeroenDeDauw** [morrisonlevi/Ardent#38]
I've been looking though this library a bit and started wondering why most methods do not have an explicit visibility declared. Is there a reason for using `function foo` rather than `public function foo`?

There are places where I am wondering if things are intentionally public or are just missing either private or protected. For instance `HashMap::areEqual`. This method does not make sense as part of this the public interface of this class. An anonymous function could be used in `contains`. Though perhaps it is done like this to allow overriding in derivatives of `HashMap`?

**Comment by morrisonlevi** [comment]
> I've been looking though this library a bit and started wondering why most methods do not have an explicit visibility declared. Is there a reason for using function foo rather than public function foo?

Yes. By not specifying `public` whenever possible this means whenever I do see a `public` visibility modifier I know that I am promoting visibility.

I believe `areEqual` was publicly visible because it used to get passed to an underlying storage component but no longer does. It can probably be private.

**Comment by JeroenDeDauw** [comment]
I'm not sure I get it. So you have public things that are not promoted as such and those that are? Does this have something to do with the scope of visibility, for instance differentiating between package public and package protected (which you cannot enforce in PHP)?

To me it's important the intent is clear. If code is explicitly defined public, it's clear to me what the intent is. If it's not explicitly defined, then things get a lot more ambiguous.

Not trying to convince you here, just curious why your approach differs from mine.

**Comment by morrisonlevi** [comment]
If a method was previously `protected` in a super-class and I change it to `public` I add the `public` keyword. This alerts me to the fact that I am widening or promoting the visibility.

**Comment by JeroenDeDauw** [comment]
Thanks for explaining
