### ISSUE TITLE
how to use and test?

### ISSUE THREAD

**Issue by damaainan** [morrisonlevi/Ardent#52]
Hello ! How to use this library ? And how to use PHPUnit to test code ? Have anyone will tell me ?
Thank you.

**Comment by morrisonlevi** [comment]
I actually recommend that you *don't* use this library. To quote from the README:

> This project is unstable and subject to significant changes from release to release. Stability is not a goal during this phase of development. To be clear: you are using this project at your own risk.
  
Especially right now I am doing a re-design of the library based on features of PHP that I am currently developing. I expect that it will change soon and the changes will be incompatible.

**Comment by damaainan** [comment]
Thank you . I use this library  only for learn data structures with php , not use in reality work . 
Hope your new project will be finished as soon as possible.
Thank you again.
